//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MyService
{
    [Serializable]
    public class MyServiceResponse : Message
    {
        public const string k_RosMessageName = "my_service/MyService";
        public override string RosMessageName => k_RosMessageName;

        public int sum;

        public MyServiceResponse()
        {
            this.sum = 0;
        }

        public MyServiceResponse(int sum)
        {
            this.sum = sum;
        }

        public static MyServiceResponse Deserialize(MessageDeserializer deserializer) => new MyServiceResponse(deserializer);

        private MyServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.sum);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sum);
        }

        public override string ToString()
        {
            return "MyServiceResponse: " +
            "\nsum: " + sum.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
