//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MyService
{
    [Serializable]
    public class MyServiceRequest : Message
    {
        public const string k_RosMessageName = "my_service/MyService";
        public override string RosMessageName => k_RosMessageName;

        public int a;
        public int b;

        public MyServiceRequest()
        {
            this.a = 0;
            this.b = 0;
        }

        public MyServiceRequest(int a, int b)
        {
            this.a = a;
            this.b = b;
        }

        public static MyServiceRequest Deserialize(MessageDeserializer deserializer) => new MyServiceRequest(deserializer);

        private MyServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.a);
            deserializer.Read(out this.b);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.a);
            serializer.Write(this.b);
        }

        public override string ToString()
        {
            return "MyServiceRequest: " +
            "\na: " + a.ToString() +
            "\nb: " + b.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
