//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MyRobotArmServiceTest
{
    [Serializable]
    public class MoverServiceResponse : Message
    {
        public const string k_RosMessageName = "my_robot_arm_service_test/MoverService";
        public override string RosMessageName => k_RosMessageName;

        public Moveit.RobotTrajectoryMsg trajectory;

        public MoverServiceResponse()
        {
            this.trajectory = new Moveit.RobotTrajectoryMsg();
        }

        public MoverServiceResponse(Moveit.RobotTrajectoryMsg trajectory)
        {
            this.trajectory = trajectory;
        }

        public static MoverServiceResponse Deserialize(MessageDeserializer deserializer) => new MoverServiceResponse(deserializer);

        private MoverServiceResponse(MessageDeserializer deserializer)
        {
            this.trajectory = Moveit.RobotTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "MoverServiceResponse: " +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
