//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SnakeArtRobot.Arm
{
    [Serializable]
    public class RobotArmMoveitJointsMsg : Message
    {
        public const string k_RosMessageName = "snake_art_robot/RobotArmMoveitJoints";
        public override string RosMessageName => k_RosMessageName;

        public double[] joints;
        public Geometry.PoseMsg goal_pose;

        public RobotArmMoveitJointsMsg()
        {
            this.joints = new double[7];
            this.goal_pose = new Geometry.PoseMsg();
        }

        public RobotArmMoveitJointsMsg(double[] joints, Geometry.PoseMsg goal_pose)
        {
            this.joints = joints;
            this.goal_pose = goal_pose;
        }

        public static RobotArmMoveitJointsMsg Deserialize(MessageDeserializer deserializer) => new RobotArmMoveitJointsMsg(deserializer);

        private RobotArmMoveitJointsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joints, sizeof(double), 7);
            this.goal_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints);
            serializer.Write(this.goal_pose);
        }

        public override string ToString()
        {
            return "RobotArmMoveitJointsMsg: " +
            "\njoints: " + System.String.Join(", ", joints.ToList()) +
            "\ngoal_pose: " + goal_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
