//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SnakeArtRobot
{
    [Serializable]
    public class ArmServiceRequest : Message
    {
        public const string k_RosMessageName = "snake_art_robot/ArmService";
        public override string RosMessageName => k_RosMessageName;

        public MyRobotArmMoveitJointsMsg joints_input;

        public ArmServiceRequest()
        {
            this.joints_input = new MyRobotArmMoveitJointsMsg();
        }

        public ArmServiceRequest(MyRobotArmMoveitJointsMsg joints_input)
        {
            this.joints_input = joints_input;
        }

        public static ArmServiceRequest Deserialize(MessageDeserializer deserializer) => new ArmServiceRequest(deserializer);

        private ArmServiceRequest(MessageDeserializer deserializer)
        {
            this.joints_input = MyRobotArmMoveitJointsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints_input);
        }

        public override string ToString()
        {
            return "ArmServiceRequest: " +
            "\njoints_input: " + joints_input.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
