//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SnakeArtRobot
{
    [Serializable]
    public class MyServiceRequest : Message
    {
        public const string k_RosMessageName = "snake_art_robot/MyService";
        public override string RosMessageName => k_RosMessageName;

        public string msg;

        public MyServiceRequest()
        {
            this.msg = "";
        }

        public MyServiceRequest(string msg)
        {
            this.msg = msg;
        }

        public static MyServiceRequest Deserialize(MessageDeserializer deserializer) => new MyServiceRequest(deserializer);

        private MyServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.msg);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.msg);
        }

        public override string ToString()
        {
            return "MyServiceRequest: " +
            "\nmsg: " + msg.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
