//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MyRobotArmService
{
    [Serializable]
    public class MoverServiceRequest : Message
    {
        public const string k_RosMessageName = "my_robot_arm_service/MoverService";
        public override string RosMessageName => k_RosMessageName;

        public MyRobotArmMoveitJointsMsg joints_input;

        public MoverServiceRequest()
        {
            this.joints_input = new MyRobotArmMoveitJointsMsg();
        }

        public MoverServiceRequest(MyRobotArmMoveitJointsMsg joints_input)
        {
            this.joints_input = joints_input;
        }

        public static MoverServiceRequest Deserialize(MessageDeserializer deserializer) => new MoverServiceRequest(deserializer);

        private MoverServiceRequest(MessageDeserializer deserializer)
        {
            this.joints_input = MyRobotArmMoveitJointsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints_input);
        }

        public override string ToString()
        {
            return "MoverServiceRequest: " +
            "\njoints_input: " + joints_input.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
